services:
  - type: web
    name: worldmorse-central
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn central_server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /v1/meta
